### ISSUE TITLE
"Measurement catalogs" never delivered; need to update documentation

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#10]
We need to update the documentation for DR1 (and DR2) where we describe the "measurement" (forced-photometry) catalogs:   http://www.legacysurvey.org/dr1/catalogs 

We never actually delivered these for DR1 and I believe the (current) plan is to not include them for DR2 either (unless someone has a chance to take a look and finds them useful!).

**Comment by geordie666** [comment]
These have now been redacted in the DR1 documentation. Will propagate through to DR2
