### ISSUE TITLE
Outdated MASKBITS documentation. 

### ISSUE THREAD

**Issue by michaelJwilson** [legacysurvey/legacysurvey#102]
http://legacysurvey.org/dr8/bitmasks/

Implies that blob-based masking still applies in MASKBITS, when in fact this has changed to a circular mask based on the stellar mag. 

'1    BRIGHT    touches a pixel in a blob containing a bright (Tycho-2) star.'

Should also indicate that either Tycho-2, or Gaia G < 13 get BRIGHT, before matching.

Thanks

Mike

**Comment by michaelJwilson** [comment]
There's also a small correction here:  http://legacysurvey.org/ccdordering/, where for 2084 MzLS exposures beyond the pole, the column ordering is reversed.

**Comment by weaverba137** [comment]
Closed by #104.
