### ISSUE TITLE
document all mask bits for DR2

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#11]
We need to document all mask values, including those over 128:
   http://legacysurvey.org/dr1/catalogs

See, for example, this part of the pipeline:
  https://github.com/legacysurvey/legacypipe/blob/master/py/legacypipe/common.py#L46-L53

**Comment by geordie666** [comment]
All bits except longthin are now documented in DR1. "longthin" was new for DR2. Will document it once the DR2 pages exist based on the following description from Dustin:

'longthin' = 1024 -- it's a mask value I add in the legacypipe processing.  In each image, I run a source detection step, find connected components above 5 sigma, and mask out objects with a major axis > 200 pixels and minor/major < 0.1 .  These are supposed to be streaks such as satellite hits.
