### ISSUE TITLE
minor photo-z wording

### ISSUE THREAD

**Issue by janewman-pitt-edu** [legacysurvey/legacysurvey#110]
I was traveling to the LSST DESC meeting yesterday so unable to do a final check till now, apologies.

I did see one thing: I think we should clarify 

"the optical-WISE color cut"
to read
"an optical-WISE color cut, as applied in Zhou et al."

**Comment by janewman-pitt-edu** [comment]
This is not urgent :)

**Comment by geordie666** [comment]
Addressed in #116.
