### ISSUE TITLE
Are MEDIUM masks forcing TYPE=PSF?

### ISSUE THREAD

**Issue by rongpu** [legacysurvey/legacysurvey#113]
In the current DR8 documentation, it says 

> Within the mask regions for bright stars, globular clusters and large galaxies, sources are forced to be TYPE=PSF

But it is unclear whether the "bright stars" include the MEDIUM stars (13<G<16). I think this is important information and should be made clear in the text.

**Comment by dstndstn** [comment]
No, MEDIUM stars do not force sources PSF, only BRIGHT ones do (BRIGHT =
Tycho-2 and Gaia stars < 13).

**Comment by geordie666** [comment]
Addressed in #116.
