### ISSUE TITLE
User-requested improvement: link to external cat docs from "overview" page

### ISSUE THREAD

**Issue by dstndstn** [legacysurvey/legacysurvey#115]
Per a helpdesk email,

Please include the link to 
http://legacysurvey.org/dr8/files/#external-files-region-external
in overview table in "Contents of DR8" on this page:
http://www.legacysurvey.org/dr8/description/#photometry

**Comment by geordie666** [comment]
This request confuses me. Any idea where to include this or why? 

As far as I can tell, the external files aren't used to compute the photometry in any way, so http://legacysurvey.org/dr8/files/#external-files-region-external doesn't seem relevant to http://www.legacysurvey.org/dr8/description/#photometry ?

**Comment by geordie666** [comment]
Oh, wait, maybe you just mean in the table at

http://www.legacysurvey.org/dr8/description/#contents-of-dr8

(rather than the photometry) I think that must be correct. That link to the "overview table" makes more sense to me.

Got it. I think.

**Comment by dstndstn** [comment]
Ahhh yes you're right

**Comment by geordie666** [comment]
Addressed in $116.
