### ISSUE TITLE
What is the fiber diameter used in FIBERFLUX?

### ISSUE THREAD

**Issue by rongpu** [legacysurvey/legacysurvey#118]
The description of FIBERFLUX is "Predicted x-band flux within a fiber from this object in 1 arcsec Gaussian seeing", and it does not mention the fiber diameter in the calculation.

**Comment by dstndstn** [comment]
Fiber diameter is 1.5";

https://github.com/legacysurvey/legacypipe/blob/master/py/legacypipe/runbrick.py#L1839

**Comment by rongpu** [comment]
Thanks!

May I request that we add this to the documentation?

**Comment by geordie666** [comment]
Yep, I'll add it (I'm closing this issue and shunting it to the DR9 docs issue.
