### ISSUE TITLE
Document DR9SV release

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey#123]
It now appears (confirmed by David Schlegel today) that the `dr9sv` release will not actually be used for SV. The full DR9 will be used instead. Thus, we need to document that, despite the name, `dr9sv` was *not*/will *not* be used for any targeting.

**Comment by geordie666** [comment]
@weaverba137: As I recall, `dr9sv` was a completely internal release. I don't _think_ I've made any reference to it on the webpages? I'll certainly remove any reference to `dr9sv` if I can find one. But, I won't be documenting `dr9a`, `dr9b` or anything else through `dr9m`. Just the final `dr9` release.

**Comment by weaverba137** [comment]
I don't think there are references to it in the documentation, but it **is public**. So I'm just trying to head off confusion >~ 1 year from now.

**Comment by geordie666** [comment]
Ah, I didn't realize `dr9sv` was public. Can you point me to the public link so I can add that link to the documentation? We can probably just add a disclaimer on the front page of the eventual `dr9` release.

**Comment by weaverba137** [comment]
`/global/cfs/cdirs/cosmo/data/legacysurvey/dr9sv`.

https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr9sv/

**Comment by geordie666** [comment]
Addressed in #125.
