### ISSUE TITLE
Legacy survey website down?

### ISSUE THREAD

**Issue by ErikOsinga** [legacysurvey/legacysurvey#124]
Hi,

I am not sure whether this is the correct place to ask this question, but the website https://www.legacysurvey.org/ has been down for me for about two days now. Just wondering if you were aware of this issue.

Kind regards,
Erik

**Comment by djschlegel** [comment]
Erik-- The host machine at NERSC will be down until around Dec 20.  Updates at https://nersc-status.lbl.gov/ .   A limited version of the Viewer is available at viewer.legacysurvey.org if that's helpful.  -David

**Comment by ErikOsinga** [comment]
That's very helpful, many thanks!
