### ISSUE TITLE
document special behavior for Sculptor and Fornax

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#130]
@dr-guangtou noticed the lack of non-Gaia sources around Fornax, which we treated (as well as Sculptor) as "globular clusters" and turned off source detection. We should more explicitly document this behavior here--
  https://www.legacysurvey.org/dr9/external/#globular-clusters-planetary-nebulae

**Comment by weaverba137** [comment]
@moustakas, did this get closed by #132 or not?

**Comment by moustakas** [comment]
@weaverba137 yes it did but note that we're still serving that content in the 'staging' site
  http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/sga/

I intend to finish up the SGA as soon as possible after Cori is back at the end of this week.

**Comment by weaverba137** [comment]
That's fine if it's not public yet, just want to make sure the text is there.

Closed by #132
