### ISSUE TITLE
remove SGA / largegalaxy files from DR9 "files" page

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#131]
These data products and files are being released semi-independently from DR9 and I am documenting them on the (still in progress) SGA page, so I propose we remove them from here--
  https://www.legacysurvey.org/dr9/files/#coming-soon-large-galaxy-files-largegalaxies-aaa-galname

**Comment by geordie666** [comment]
We likely won't serve a new version of the webpages until you've updated the SGA page. And, it's made fairly clear on the existing page that this product is "coming soon."

So, there's no real point to removing that page now. Although, you should definitely remove that page in your updated version of the webpages, and point the SGA links to wherever you would like.
