### ISSUE TITLE
Mask radius

### ISSUE THREAD

**Issue by rongpu** [legacysurvey/legacysurvey#135]
We should clarify that the "radius-magnitude relation" (https://www.legacysurvey.org/dr9/bitmasks/#maskbits) for the Tycho-2 and GAIA stars are for the MEDIUM mask, and that the BRIGHT mask radius are exactly half of that.

Similarly, we should clarify that the "radius" in the GAIA mask catalog (https://www.legacysurvey.org/dr9/files/#gaia-mask-dr9-fixed-fits) is the MEDIUM mask radius.

**Comment by rongpu** [comment]
I just noticed that the radius-magnitude relation links still points to the DR8 version, but the relation has changed in DR9, so we should update the link to point to the DR9 version:

https://github.com/legacysurvey/legacypipe/blob/6d1a92f8462f4db9360fb1a68ef7d6c252781027/py/legacypipe/reference.py#L319

(This is the MEDIUM mask radius, and it applies to both for both GAIA and Tycho-2 magnitudes)

**Comment by geordie666** [comment]
Ah, yes, nice catch. I'll fix that in #136 before merging (when I get a chance!).

**Comment by weaverba137** [comment]
Closed by #136.
