### ISSUE TITLE
Units in tractor files

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey#158]
There is an inconsistency between the [tractor catalog description](https://www.legacysurvey.org/dr9/catalogs/) and the actual tractor FITS files.  The former lists photometric flux units as 'nanomaggies', but when you actually open a tractor file and read the units in the file, the spelling is 'nanomaggy'.

Leaving aside the issue that nanomagg(y|ies) is not a FITS-standard unit, there are additional problems with the unit notation in tractor files: `1/unit` or `1/unit^2` is invalid, no matter what `unit` is.  The correct notation is `unit^-1` or `unit-2` or `unit**-1`.  So for example, `1/deg^2` should actually be `deg**-2`.

See also desihub/desidatamodel#129.

**Comment by dstndstn** [comment]
@djschlegel should the unit by "nanomaggy" or "nanomaggie"?

**Comment by djschlegel** [comment]
I think we have always used nanomaggy / nanomaggies for singular / plural.  But maybe plural is really the only relevant name in practice.

**Comment by weaverba137** [comment]
This issue actually breaks down into three sub-issues:

1. nanomaggy and nanomaggies may be fine for taking about the unit in general, but what is the *symbol* for the unit that belongs in the actual data file?  For example, in a FITS data file, we don't use "second" or "seconds", we use `s`; we don't use "degree" or "degrees" we use `deg`.
2. Regardless of what the actual name of the unit is supposed to be, there is currently an *inconsistency* between the documentation and the actual data files.  The documentation should match the actual data files.
3. Assuming this issue results in the units in the actual data files *changing*, then we also need to keep the documentation in sync with that future change.

**Comment by weaverba137** [comment]
@geordie666, has this issue been resolved for DR10, or otherwise mentioned as a known issue?

**Comment by geordie666** [comment]
Thanks for remembering this point @weaverba137. Some of the units in the Tractor files _have_ changed, so I should review my use of units on the documentation pages. I'm out of time today, but I should be able to conduct that review (very) early tomorrow morning (Mountain time). Again, I don't think this should block a "soft" release of the DR10 documentation if you're pushed for time.

Such a review will only partially address your original issue, though, as some units are still expressed as, e.g, `1/nanomaggy^2` and `1/arcsec^2`, while you were advocating for the FITS-standard `nanomaggy**-2` and `arcsec**-2`.

**Comment by weaverba137** [comment]
I'm definitely not asking for any changes to the actual files at this point. The main thing I'd like to see right now is consistency of spelling, *i.e.* is it `nanomaggy` or `nanomaggies`?

**Comment by geordie666** [comment]
Colloquially, there is no convention. David prefers nanomaggies (see above) the files adopt `nanomaggy`.

If we're seeking consistency between the Tractor catalog headers and the documentation, then I should update the documentation to use `nanomaggy`, throughout. _But_ if we're searching for complete consistency, then we should drop some useful information from the documentation that is missing from the files. For example, the documentation includes units of:

- `pix` for `bx`, `by` and `wise_x`, `wise_y`.
- `days` for `mjd_min` and `mjd_max`.
- `yr` for `ref_epoch`.
- `magnitudes` for `gaia_a_g_val` and `gaia_e_bp_min_rp_val` (adopted from the Gaia data model).
- `mas` for `gaia_astrometric_sigma5d_max` (adopted from the Gaia data model).
- `arcsec^2` for `nea_g`, `nea_r`, `nea_i` and `nea_z`, and `blob_nea_g`, `blob_nea_r`, `blob_nea_i` and `blob_nea_z`.

These units are all missing from the headers of the Tractor catalogs. This would seem like useful information to discard?

I have only had time to review the actual Tractor catalogs. There may be various other inconsistencies where the documentation includes details that the files lack.

**Comment by weaverba137** [comment]
Right, I just want to see the spelling in the documentation match the spelling in the actual files.

> This would seem like useful information to discard?

I assume this is a typo?

We can worry about other files as issues come up. If you've reviewed the tractor files, that's fine for now.

**Comment by geordie666** [comment]
This would seem like useful information to discard?

No, this isn't a typo: I think it would be useful for users to have a synopsis of the units of certain quantities even if they have not been included in the headers of the appropriate files.

**Comment by geordie666** [comment]
To put it another way, we have a choice:

(1) Discard useful information from on units from "synopsis" tables to maintain consistency between the Tractor files and documentation.
(2) Retain that useful information but have inconsistencies between the Tractor files and documentation.

**Comment by weaverba137** [comment]
Sorry, I don't understand what you mean by "discard".  In my mind, "discard" means "throw away", "delete", and, also, in my mind, one should never, ever delete useful information.  Instead, we should point out where information is missing in the headers, and identify the authoritative source for the information.  That is *not* an inconsistency, that is simply documenting information that is missing from the files.

**Comment by geordie666** [comment]
I don't think it's as useful to include units outside of the "synopsis" tables with a lengthy description of why the units are missing from the file headers, why we've chosen to include them anyway, where users should visit to check our adopted units are authoritative, etc. 

Sure, users can go digging for information elsewhere on the web pages — but, because we _do_ include units in the "synopsis" tables of quantities, that's where users will look for units. Expanding my list of options:

(1) Discard units from the "synopsis" table to maintain consistency between the Tractor files and documentation.
(2) Retain that useful information but have inconsistencies between the Tractor files and documentation in the "synopsis" table.
(3) Move some information about units out of the "synopsis" table and place it elsewhere on the web pages, where users might not find it if they're just quickly trying to determine the appropriate unit for a quantity.

By the "synopsis" table, here, I mean the table at, e.g., https://www.legacysurvey.org/dr9/catalogs/ that has the header-row: 
```
Name | Type | Units | Description
```
I'm comfortable with having some inconsistencies (option 2) because I think including more information about units (in the standard place where we list units) is a good thing for usability. But if you want complete consistency, we'd have to remove some of those units from the "synopsis" table (option 1). I, personally, don't like including information about units that aren't in the Tractor files in a different place beyond the "synopsis" table (option 3).

**Comment by weaverba137** [comment]
> I don't think it's as useful to include units outside of the "synopsis" tables with a lengthy description of why the units are missing from the file headers, why we've chosen to include them anyway, where users should visit to check our adopted units are authoritative, etc.

The authoritative source *is* the synopsis table in the case where units are missing from the file headers. I'm sorry if I implied that there had to be an additional authoritative source elsewhere.

Again: if we're documenting something that is *missing* from the files, that is not an inconsistency.  An inconsistency is where the documentation *conflicts* with information that *is* in the files.

**Comment by geordie666** [comment]
Ah, OK, I think I understand your position, now. In that case, I think the minimal change would be replacing `nanomaggies` with `nanomaggy` in the documentation. I should have time to do that in the next hour or so.

**Comment by weaverba137** [comment]
Yes, that's fine. Thank you.

**Comment by geordie666** [comment]
I've made this change for DR10, at least (in PR #165). I will update the corresponding tables for earlier Data Releases once I've had a chance to review the Tractor files in earlier DRs for consistency. I won't complete that review until (early) tomorrow, but I can make the changes in a separate PR, if necessary.

**Comment by weaverba137** [comment]
That's also fine.

**Comment by geordie666** [comment]
I've now updated the Tractor catalog headers for consistency for all of DR1-10 (in PR #165).

**Comment by geordie666** [comment]
I've now also updated the documentation for the units in the other files on the "files" pages to be consistent with the headers for DR9 and DR10 (in PR https://github.com/legacysurvey/legacysurvey/pull/165). Most notably the "sweep" files, which are directly derived from the Tractor files. We didn't start providing units in the sweep files until DR9.

**Comment by weaverba137** [comment]
Closed by #165. We can open other, more specific issues for specific cases.
