### ISSUE TITLE
Update sky viewer "tips & tricks" with a little more information

### ISSUE THREAD

**Issue by dstndstn** [legacysurvey/legacysurvey#159]
- if fetching FITS cutouts with pixscale=0.262, you get nanomaggies
- adding &subimage yields cutouts from (possibly multiple) overlapping brick images (rather than resampled images)

**Comment by weaverba137** [comment]
@dstndstn, has this made it into the DR10 branch?

**Comment by dstndstn** [comment]
Hi Ben, I'm (still) wrapping up the final DR10 viewer things and I hope to deploy it to the production viewer today.

**Comment by dstndstn** [comment]
But if your question is whether the viewer has/will have this property for DR10, then that's a yes.

**Comment by weaverba137** [comment]
That's not my exact question, sorry. By "DR10 branch", I meant the DR10 documentation branch, `ADM-dr10`, of this product. Has the documentation been updated to reflect the changes to the production viewer?

**Comment by dstndstn** [comment]
Okay, I just updated the ADM-dr10 branch to include these tips & tricks.  Thanks!

**Comment by weaverba137** [comment]
Closed by #165.
