### ISSUE TITLE
Known issues for DR10

### ISSUE THREAD

**Issue by geordie666** [legacysurvey/legacysurvey#160]
I'm starting this thread to keep track of known issues for DR10. Anyone should feel free to add any issues!

- Rings of spurious Gaia sources around bright stars ([decam-chatter 16786]).
- Detection is also now done in i-band, both in the initial z-i-r-g per-band detection step and in the per-source SED fitting. This isn't strictly an issue, but it needs to be added to the DR10 description page.

**Comment by weaverba137** [comment]
I don't actually see any mention of the spurious sources in the known issues page.

**Comment by geordie666** [comment]
When I reviewed the ticket I realized this was an issue with Gaia, not with the Legacy Surveys. But, I didn't immediately close this issue as the other point (about z-i-r-g per-band detection) needed to be retained.

**Comment by weaverba137** [comment]
OK, thanx.

**Comment by weaverba137** [comment]
Closed by #165.
