### ISSUE TITLE
Further update to the short acknowledgment

### ISSUE THREAD

**Issue by geordie666** [legacysurvey/legacysurvey#163]
Another update to the "short" acknowledgement just came down from management. The text should read:

The DESI Legacy Imaging Surveys consist of three individual and complementary projects: the Dark Energy Camera Legacy Survey (DECaLS), the Beijing-Arizona Sky Survey (BASS), and the Mayall z-band Legacy Survey (MzLS). DECaLS, BASS and MzLS together include data obtained, respectively, at the Blanco telescope, Cerro Tololo Inter-American Observatory, NSF’s NOIRLab; the Bok telescope, Steward Observatory, University of Arizona; and the Mayall telescope, Kitt Peak National Observatory, NOIRLab. NOIRLab is operated by the Association of Universities for Research in Astronomy (AURA) under a cooperative agreement with the National Science Foundation. Pipeline processing and analyses of the data were supported by NOIRLab and the Lawrence Berkeley National Laboratory. Legacy Surveys also uses data products from the Near-Earth Object Wide-field Infrared Survey Explorer (NEOWISE), a project of the Jet Propulsion Laboratory/California Institute of Technology, funded by the National Aeronautics and Space Administration. Legacy Surveys was supported by: the Director, Office of Science, Office of High Energy Physics of the U.S. Department of Energy; the National Energy Research Scientific Computing Center, a DOE Office of Science User Facility; the U.S. National Science Foundation, Division of Astronomical Sciences; the National Astronomical Observatories of China, the Chinese Academy of Sciences and the Chinese National Natural Science Foundation. LBNL is managed by the Regents of the University of California under contract to the U.S. Department of Energy. The complete acknowledgments can be found at https://www.legacysurvey.org/.

The currently missing sentences appear to be:

- Pipeline processing and analyses of the data were supported by NOIRLab and the Lawrence Berkeley National Laboratory.
- LBNL is managed by the Regents of the University of California under contract to the U.S. Department of Energy.

**Comment by weaverba137** [comment]
@geordie666, I've been noticing that I'm hearing about these issues second-hand.  If I am not actually assigned to an issue or otherwise tagged, I won't get notified.

And I even specifically asked whether that needed to be included in relation to #157.

**Comment by geordie666** [comment]
Indeed, my intention was not to assign you to this issue specifically — although I greatly appreciate that you've written a PR to address it. 

I was only made aware of the additional sentences about 10 minutes before I posted this issue — long after we closed #157. So, I also applaud your prescience.
