### ISSUE TITLE
Continuing minor updates to the documentation

### ISSUE THREAD

**Issue by geordie666** [legacysurvey/legacysurvey#170]
The [acknowledgments page](https://www.legacysurvey.org/acknowledgment/) incorrectly links to https://www.legacysurvey.org/acknowledgment/sga/sga2020 instead of https://www.legacysurvey.org/sga/sga2020.

h/t Stephen Bailey.

**Comment by geordie666** [comment]
While I'm making a list of minor updates before we post another version of the pages:

Under Astrometry [on the DR10 pages](https://www.legacysurvey.org/dr10/description/#astrometry) we should state "difference between the position of Gaia stars at an epoch of 2015.0 and the epoch of the DR10 image." rather than "difference between the position of Gaia stars at an epoch of 2015.0 and the epoch of the DR9 image."

h/t Mara Salvato.

**Comment by moustakas** [comment]
Piggy-backing on this ticket, the BASS url no longer seems to be working / correct:

**Comment by geordie666** [comment]
Again, for the next set of updates (which I should get to soon now we're done with EDR!): @stephjuneau requested improved documentation about PMRA (and whether we include the cos-dec term).

**Comment by moustakas** [comment]
Another minor update: The `Myers et al. (2022)` reference should be updated to 2023, here and likely elsewhere--
  https://www.legacysurvey.org/dr9/files/#random-catalogs-randoms

Also, should we include a link / splash from the imaging home page back to the DESI/EDR public pages?

**Comment by moustakas** [comment]
https://github.com/legacysurvey/legacypipe/issues/680 was posted to the `legacypipe` repo but at this point it's a DR9/DR10 documentation issue and should be documented in both the [DR9 Known Issues](https://www.legacysurvey.org/dr9/issues) and the [DR10 Known Issues](https://www.legacysurvey.org/dr10/issues) pages.

Basically, the issue means that the `maskbits` images for the bricks with these 52 galaxies do not have the `GALAXY` bit set even though they should.

**Comment by moustakas** [comment]
This ticket could also just be documented as a "Known Issue" and then closed--
https://github.com/legacysurvey/legacypipe/issues/639

**Comment by weaverba137** [comment]
@geordie666, wasn't this closed by #172, or are there remaining issues not addressed in that PR?

**Comment by geordie666** [comment]
Closed by #172.
