### ISSUE TITLE
Update morphology table for 10.1

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey#176]
The Morphological Classification table, https://www.legacysurvey.org/dr10/description/#morphological-classification, still reflects 10.0. Please update with DR10.1 numbers.

**Comment by geordie666** [comment]
Not updating the bricks files for DR10.1 was just an oversight, I think. In any case, Dustin will run the DR10.1 versions of those files soon and then I'll add the additional numbers to the documentation. Hopefully by the end of the week.

**Comment by weaverba137** [comment]
Closed by #177.
