### ISSUE TITLE
final changes for DR2

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#22]
* Change DR2 release date to January 2016 (unless there are reasons to keep Dec 2015)
* In 'files' specify that 'decals-dr2-specObj-dr12.fits', 'decals-dr2-DR12Q.fits', and 'decals-dr2-Superset_DR12Q.fits' can be found in the 'external' subdirectory.
* The 'issues' page (http://legacysurvey.org/test/dr2/issues) is called "Known Issues and fixes" but the page linking to it is called "Known Issues and Workarounds".  Pick a side we're at war.

**Comment by geordie666** [comment]
Fixed set of issues #22
