### ISSUE TITLE
Berkeley Lab logo is not visible on legacysurvey.org

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey#26]
The Berkeley Lab logo, nominally files/Berkeley_Lab_Logo_Small.png, does not appear on the legacysurvey.org front page, probably due to a permission issue.

It would also be great if there were instructions on how to login to and deploy on legacysurvey.org.

**Comment by weaverba137** [comment]
@djschlegel In order to fix this, you must log in to NERSC and

```
cd /project/projectdirs/cosmo/webapp
chgrp -R cosmo legacysurvey
find legacysurvey -type f -exec chmod 0664 \{\} \;
find legacysurvey -type d -exec chmod 2775 \{\} \;
rm legacysurvey/png
rm legacysurvey/.DS_Store
rm -rf legacysurvey/foobar
rm -rf legacysurvey/team
rm -rf legaxysurvey/decals
```
This should get not only the permissions but the directory structure closer to what is *actually* in the Nikola source files.

I will be watching to make sure this happens promptly.

**Comment by weaverba137** [comment]
Looks like this is done!

**Comment by djschlegel** [comment]
This file at NERSC wasn't world-readable.  I have no idea why, and the file in the git repo has good permissions, so I just fixed the copy at NERSC.
