### ISSUE TITLE
incorrect documentation on depth tags

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#28]
The depth tags documented on http://legacysurvey.org/dr2/catalogs should be
```
DECAM_DEPTH
DECAM_GALDEPTH
```
not
```
DEPTH
GALDEPTH
```

**Comment by geordie666** [comment]
Fixed…see https://github.com/legacysurvey/legacysurvey/blob/master/pages/dr2/catalogs.rst
