### ISSUE TITLE
sweep files not documented in data model

### ISSUE THREAD

**Issue by sbailey** [legacysurvey/legacysurvey#33]
I couldn't find a description of which columns are included in the sweep files as part of the data model.  Here is where I looked:

http://legacysurvey.org/dr2/catalogs/
http://legacysurvey.org/dr2/files/

The meaning of the columns are all documented as part of the tractor catalog data model, but it would still be useful to have a raw list of columns in the sweep files, or an extra column in the tractor data model flagging whether a column is included in the sweeps or not.

**Comment by geordie666** [comment]
Added description of sweeps files as part of merge #35: https://github.com/legacysurvey/legacysurvey/pull/35
