### ISSUE TITLE
minor depth documentation fix

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#70]
In http://legacysurvey.org/dr3/files (sweep files) and http://legacysurvey.org/dr3/catalogs (tractor catalogs) we document ```DECAM_DEPTH``` and ```DECAM_GALDEPTH``` as being scalars, when in fact they are 6-element arrays.  Should be a simple fix.

Also, is there any way to add a table of contents or a hash reference to these (very long!) pages, e.g., http://legacysurvey.org/dr3/files#sweeps?

**Comment by geordie666** [comment]
I've fixed this as part of the DR4 website updates on the DR4updatesADM branch...I won't issue a PR on those updates for a while, but you can consider this closed.

(I couldn't find an obvious was to link internally on pages, but I'll keep digging)
