### ISSUE TITLE
Document external catalogs for DR8

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey#87]
There are five external catalogs that are used as inputs to the DR8 pipeline:

1. PS1
2. Gaia
3. Tycho2
4. NGC
5. Large Galaxies

We want to move these into an archival state, but for the purposes of **DR8** we should just document that these catalogs are a requirement of the pipeline.

Here are some questions that should be answered in documentation:

* What is the *provenance* of these catalogs?  Are they just downloaded and used as-is from a public site, or have they been processed further?
* What is the data model for these catalogs?
* How can an expert (with a NERSC account with cosmo access) find these catalogs?

Finally it should be stated that these catalogs will be available to the public in a static, archival state for **DR9**.

**Comment by dstndstn** [comment]
1.  PS1 -- These files were produced by Doug Finkbeiner.  At the time they were produced, I believe they were proprietary Pan-STARRS1 data, but will now be public with PS1-DR1.  I believe these have mag, color, and morphology cuts? but not certain.
Data model is that they are Nside=32 healpix tiles each containing a FITS table.
/global/project/projectdirs/cosmo/work/ps1/cats/chunks-qz-star-v3

2.  Gaia -- These are Nside=32 healpix tiles, each containing a FITS table.  They contain all sources from the Gaia-DR2 public data release.  Provenance is documented in
/global/project/projectdirs/cosmo/work/gaia/chunks-gaia-dr2-astrom-2/README
and /global/project/projectdirs/cosmo/staging/gaia/dr2/README
Files are in /global/project/projectdirs/cosmo/work/gaia/chunks-gaia-dr2-astrom-2

3.  Tycho-2 -- Tycho-2 star catalog, produced from the original binary .dat files, and augmented with an "isgalaxy" column, plus J,H,K and estimated z mags.  Provenance described in
/global/project/projectdirs/cosmo/staging/tycho2/README

4. NGC/IC catalog isn't used any more.

**Comment by weaverba137** [comment]
Closed by #89.
