### ISSUE TITLE
Mention model and resid layers in cutout server

### ISSUE THREAD

**Issue by dstndstn** [legacysurvey/legacysurvey#88]
from http://discuss.legacysurvey.org/t/is-there-an-equivalent-cutout-service-for-models-and-residuals/1090

> "Sections of DECaLS for DR7 can be obtained as JPEGs […] files using the cutout service, as > follows:
> 
> JPEG: http://legacysurvey.org/viewer/jpeg-cutout?ra=190.1086&dec=1.2005&layer=decals-dr7&pixscale=0.27&bands=grz"
> 
> Is there something similar for obtaining cutouts for models? residuals?

**Comment by geordie666** [comment]
I added this to the pages as far back as DR6. As with the other issues, nothing will change on the website until we serve the DR8 version.

**Comment by weaverba137** [comment]
Closed by #89.
