### ISSUE TITLE
documentation for decals-specz.fits is incorrect

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacysurvey#9]
The documentation for decals-specz.fits (http://www.legacysurvey.org/dr1/files) states that HDU4 holds the WISE forced photometry.   This is incorrect -- a hold-out from the Early Data Release when we simply matched against Dustin's existing forced-photometry (SDSS+WISE) catalogs. 

In DR1 (and thereafter) the decals-specz.fits file only has three extensions, and the WISE photometry is included with the 1st extension (with the Tractor/DECam photometry).

**Comment by geordie666** [comment]
This should now be corrected in the DR1 documentation
