### ISSUE TITLE
Updates in the wake of the DR8 release.

### ISSUE THREAD

**Issue by geordie666** [legacysurvey/legacysurvey#91]
For the DR8 pages, we need to add or change the following in the short-term:

- On the description page, the cut-off dates for the non-DECaLS DECam observations are incorrectly based on the `survey-ccds-*-dr8.fits.gz` instead of the `survey-ccds-*-dr8.kd.fits` files. The correct start/end dates are 1 September 2013 to 7 March 2019.
- On the description page, switch to: "The projections for the g,r,z filters are identical. The projections for the four WISE filters are the same except for a pixel scale of 2.75 arcsec instead of 0.262 arcsec." (add the WISE information).
- On the description page in the _Morphological Classification_ section, include “DEV” and “EXP” after the first instance of the words deVaucouleurs and exponential.
- Switch to the DR8 status plots instead of the DR7 ones.
- Document what we did for large galaxies: timeouts (coadds only) or bailouts (coadds + tractor catalogs, but with the BAILOUT masking); in the north, this is only Andromeda and M13 GC (see [legacypipe issue #390](https://github.com/legacysurvey/legacypipe/issues/390)).

**Comment by dstndstn** [comment]
I just sent #93 for the DR8 status plots

**Comment by weaverba137** [comment]
From the description of `objid`: "Catalog object number within this brick; a unique identifier hash is release,brickid,objid; objid spans [0,N-1] and is contiguously enumerated within each blob".  Within each *blob*?  Shouldn't that be *brick*?

**Comment by dstndstn** [comment]
@weaverba137 Yes, objids should be 0 to N-1 per *brick*.  Good catch.

**Comment by dstndstn** [comment]
Risa pointed out that we should mention DES specifically, since we're now pulling in a pretty big chunk of their data.  I'll send a PR.

**Comment by geordie666** [comment]
Addressed in a combination of #93, #94 and #95.

**Comment by weaverba137** [comment]
All PRs have now been merged, closing.
