### ISSUE TITLE
Classification numbers

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey#92]
We did a test load of the *north* tractor files and got these numbers:
```
select type, count(*) from ls_dr8.tractorn group by type;
 type |   count
------+-----------
 COMP |    236170
 DEV  |  16893930
 DUP  |     49764
 EXP  |  26708702
 PSF  | 155383987
 REX  | 160268419
```
Which do not agree with http://legacysurvey.org/dr8/description/#morphological-classification

Note also that these numbers are *larger* than those officially reported.

**Comment by dstndstn** [comment]
Did you cut on PRIMARY?

**Comment by weaverba137** [comment]
Are you saying that the definition of "All Northern Sources" is not really **all** but **all primary**?

**Comment by geordie666** [comment]
Personally, I think that is implied by the row-heading:

```Objects in a Primary brick```

It would seem strange to me if the other rows then _weren't_ primary. 

This is how we've reported the rows in previous data releases. But I'll make it explicit in the next version if you feel strongly about it.

For completeness, here's how the numbers are calculated:
```
import fitsio
import numpy as np
north = fitsio.read("/global/project/projectdirs/cosmo/work/legacysurvey/dr8/north/survey-bricks-dr8-north.fits.gz")
for i in north.dtype.names[9:16]:
    print(i, np.sum(north[i]))
````

**Comment by weaverba137** [comment]
Just to make sure, by reading from survey-bricks-dr8-north, there is an implicit cut on PRIMARY?

**Comment by geordie666** [comment]
I think so, but I'll let @dstndstn explicitly answer that. I've been assuming as such for the documentation, and probably inherited that information from somewhere (or checked against some other numbers).

If @dstndstn doesn't know off-hand, I'll dig in the `legacypipe` code tomorrow and get you an answer (and make sure it propagates to the documentation).

**Comment by geordie666** [comment]
Actually, our own documentation regarding the 

```

nobjs | int16 | Total number of BRICK_UNIQUE objects in this brick, of all types
npsf | int16 | Total number of BRICK_UNIQUE objects in this brick, of type PSF
nsimp | int16 | Total number of BRICK_UNIQUE objects in this brick, of type REX
nrex | int16 | Total number of BRICK_UNIQUE objects in this brick, of type REX
nexp | int16 | Total number of BRICK_UNIQUE objects in this brick, of type EXP
ndev | int16 | Total number of BRICK_UNIQUE objects in this brick, of type DEV
ncomp | int16 | Total number of BRICK_UNIQUE objects in this brick, of type COMP
```
So, yes, I believe that there is an implicit cut on PRIMARY (`BRICK_UNIQUE`).

**Comment by dstndstn** [comment]
Yes, here's the cut
https://github.com/legacysurvey/legacypipe/blob/master/py/legacyanalysis/brick-summary.py#L624

**Comment by geordie666** [comment]
@weaverba137: Perhaps it would clarify things if I took more care to use the terminology `BRICK_PRIMARY` everywhere? It seems that I drift between `PRIMARY`, `BRICK_PRIMARY` and `BRICK_UNIQUE` in places.

**Comment by weaverba137** [comment]
@geordie666, that is worth checking.  For the purposes of this issue, the important thing that we've already established is that we need to cut on primary to compare the numbers in the database.

**Comment by weaverba137** [comment]
```
select type, count(*) from ls_dr8.tractorn where brick_primary=1 group by type;
 type |   count
------+-----------
 COMP |    224490
 DEV  |  16277869
 DUP  |     44358
 EXP  |  25881826
 PSF  | 150490300
 REX  | 156474503
(6 rows)
```

**Comment by weaverba137** [comment]
We're getting closer but we're still not there.  Is there some other cut that we're missing?

**Comment by weaverba137** [comment]
@dstndstn, between the cut you mentioned and this line: https://github.com/legacysurvey/legacypipe/blob/master/py/legacyanalysis/brick-summary.py#L708, where is `T` actually written out?

**Comment by dstndstn** [comment]
We go through all the nexp files, read the corresponding tractor file and
apply the brick_primary cut, then stuff the various arrays.  They get
packed into the final table and written out at the end.

I verified that the number of unique bricks for which there are nexp files,
93610, matches both the number of rows in the brick-summary file and the
number of tractor files in dr8-north.

I find it mysterious that you have *more* objects.

Could you count the number of distinct bricknames you have?

Thanks!

**Comment by weaverba137** [comment]
93610, via `SELECT COUNT(*) FROM (SELECT DISTINCT brickname FROM ls_dr8.tractorn) AS nbrick;`

**Comment by dstndstn** [comment]
Thanks Ben, so that looks correct.

I re-read all the tractor catalogs and counted the BRICK_PRIMARY sources in
each TYPE class; I confirm Adam's numbers on legacysurvey.org.

I'm not sure what the best way is going to be to track this down.  We could
start bisecting the sky to see where your extra objects are...  Please let
me know how you'd like to proceed.

**Comment by weaverba137** [comment]
The total number of rows in the north table is 359,540,972.  I'm trying to verify that the combination release, brickid, objid is genuinely unique.  If it is genuinely unique, the number of unique (release, brickid, objid) should equal the number of rows.

**Comment by weaverba137** [comment]
And I do confirm that (release, brickid, objid) is genuinely unique.

**Comment by weaverba137** [comment]
Is there a quick way to get the total number of rows in the north tractor catalog files?

**Comment by weaverba137** [comment]
More weirdness:  If I add along the *columns* of http://legacysurvey.org/dr8/description/#morphological-classification, the number of classified objects does not add up to the total number of objects.  For example:
```
149,886,575 + 155,668,648 + 25,746,175 + 16,195,657 + 223,403 = 347,720,458 != 347,764,539
```

**Comment by geordie666** [comment]
I think the "more weirdness" is because I don't include the ``DUP`` sources in the table at http://legacysurvey.org/dr8/description/#morphological-classification. 

This was a conscious choice because the ``DUP`` sources don't have a specific entry in the ``survey-bricks-dr8-*.fits.gz`` files. Presumably they are in the counts for "all" objects, though (the ```nobjs``` column from http://legacysurvey.org/dr8/files/#survey-bricks-fits-gz).

**Comment by weaverba137** [comment]
@geordie666, OK, but I think that could be documented more clearly, unless you want to answer questions about why those numbers don't add up.  Unfortunately that still doesn't address why we have more rows in the database than the numbers in the table.

**Comment by weaverba137** [comment]
I take back what I said earlier:

> And I do confirm that (release, brickid, objid) is genuinely unique.

In fact, the number of rows in the database is greater than the number of distinct values of (release, brickid, objid), which indicates that we somehow have some duplicates in the database.

Do we have a *iron-clad* guarantee on the tractor files side that there are *zero* duplicates of (release, brickid, objid) in the tractor files?  This has nothing to do with the `DUP` morphological classification.

**Comment by dstndstn** [comment]
I believe that to be true, but am currently running a script on the
dr8-north tractor files to verify.

**Comment by dstndstn** [comment]
Hi Ben,
My script finished and it confirmed that claim.

**Comment by weaverba137** [comment]
Thank you @dstndstn !  I have confirmed that we have identical rows in the database table, so we're working to reload it.  I'll close this once we've confirmed the numbers with the new load.

**Comment by weaverba137** [comment]
After the latest reload of the tractor north files, we now find the exact same numbers.
