### ISSUE TITLE
Document equatorial MzLS fields

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey#97]
@stephjuneau and possibly others have been confused by the presence of equatorial fields in MzLS data.  That is, the "north" tractor catalog is not strictly limited to Dec >= 32.  If this is already documented, where is it documented, so we can refer people to it?  If it is not documented, obviously it should be.  I remember taking images of these fields (though it took me a while), but I can't remember *why*.

**Comment by geordie666** [comment]
I suppose the logical place to record that there are a small number of fields not at Dec >= 32 is on the survey description pages, e.g.:

http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/output/mzls/
http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/output/bass/

I too, can't remember why these fields were taken. Perhaps to obtain early overlap regions between BASS/MzLS and DECaLS.

**Comment by geordie666** [comment]
@schlafly, @djschlegel, @moustakas, @dstndstn: Can anyone remember why we took equatorial exposures, outside of the normal MzLS footprint? I _think_ BASS took some, too, although I can't easily check that for sure while NERSC is down.

**Comment by moustakas** [comment]
I believe these are spectroscopic/targeting truth fields like COSMOS. We
did these early on.

**Comment by djschlegel** [comment]
We were supposed to cover 200 sq deg on the equator as part of a required (according to the DESI imaging requirements doc DESI-1179) 450 sq deg overlap between the northern + DECam surveys.  But we only got part of that :<

**Comment by weaverba137** [comment]
OK, so who is going to take the responsibility to document this, so we can get it into the public site relatively soon?

**Comment by geordie666** [comment]
@weaverba137: I've already documented this in https://github.com/legacysurvey/legacysurvey/pull/95. I just haven't pushed my (few) new changes yet. In that branch, I'll address:

- This issue.
- The new data model for the forced photometry files once they're finalized.
- @stephjuneau's Data Lab text, once it's finalized.

Sorry, I should have mentioned that sooner to avoid duplicating effort.

If you'd like me to push what I have already so you can merge and serve it, and then I'll create additional PRs down-the-road for you to merge-and-serve, just let me know.

**Comment by weaverba137** [comment]
@geordie666 thank you for the update, please at least push what you have so I can take a look before merging.

**Comment by weaverba137** [comment]
Closed by #95.
